### ISSUE TITLE
Add "when" version number option to extension parameters

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#53]

**Comment by dhower-qc** [comment]
fixed in #102

**Comment by james-ball-qualcomm** [comment]
Actually, doesn't seem fixed yet. Still seeing CONFIG_PTR_ADDRESS in MC-1 CRD. 

![image](https://github.com/user-attachments/assets/74b2a2e3-306d-494a-9e46-62603250d4c9)

**Comment by dhower-qc** [comment]
fixed in #103

**Comment by james-ball-qualcomm** [comment]
This is still not fixed. Can you please fix it soon? There are other CSRs still showing up too (see https://github.com/riscv-software-src/riscv-unified-db/issues/163)
